package com.amadeus.web.mapper;

import com.amadeus.domain.model.User;
import com.amadeus.web.dto.CreateUserRequest;
import com.amadeus.web.dto.UpdateUserRequest;
import com.amadeus.web.dto.UserDTO;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests para UserMapper
 * 
 * Verificamos:
 * - Conversión correcta Entity -> DTO
 * - Conversión correcta Request -> Entity
 * - Actualización parcial de entidad
 * - Manejo de nulls
 */
@DisplayName("UserMapper Tests")
class UserMapperTest {

    @Test
    @DisplayName("Should convert User entity to UserDTO")
    void shouldConvertEntityToDTO() {
        // ARRANGE
        User user = User.builder()
                .id("user-123")
                .email("test@amadeus.com")
                .username("testuser")
                .passwordHash("$2a$10$hashedPassword")
                .profileImage("https://example.com/avatar.jpg")
                .createdAt(LocalDateTime.of(2024, 1, 1, 12, 0))
                .build();

        // ACT
        UserDTO dto = UserMapper.toDTO(user);

        // ASSERT
        assertNotNull(dto);
        assertEquals("user-123", dto.id());
        assertEquals("test@amadeus.com", dto.email());
        assertEquals("testuser", dto.username());
        assertEquals("https://example.com/avatar.jpg", dto.profileImage());
        assertEquals(LocalDateTime.of(2024, 1, 1, 12, 0), dto.createdAt());

        // IMPORTANTE: DTO NO debe contener passwordHash
        // (verificamos que no podamos accederlo)
    }

    @Test
    @DisplayName("Should return null when converting null entity to DTO")
    void shouldReturnNullWhenEntityIsNull() {
        // ACT
        UserDTO dto = UserMapper.toDTO(null);

        // ASSERT
        assertNull(dto, "Should return null for null entity");
    }

    @Test
    @DisplayName("Should handle null profileImage in entity to DTO conversion")
    void shouldHandleNullProfileImageInDTO() {
        // ARRANGE
        User user = User.builder()
                .id("user-123")
                .email("test@amadeus.com")
                .username("testuser")
                .passwordHash("hash")
                .createdAt(LocalDateTime.now())
                .profileImage(null) // Sin imagen de perfil
                .build();

        // ACT
        UserDTO dto = UserMapper.toDTO(user);

        // ASSERT
        assertNotNull(dto);
        assertNull(dto.profileImage(), "ProfileImage should be null");
    }

    @Test
    @DisplayName("Should convert CreateUserRequest to User entity")
    void shouldConvertRequestToEntity() {
        // ARRANGE
        CreateUserRequest request = new CreateUserRequest(
                "new@amadeus.com",
                "newuser",
                "plainPassword123" // Password en texto plano (lo hasheamos antes)
        );
        String hashedPassword = "$2a$10$hashedPassword";

        // ACT
        User user = UserMapper.toEntity(request, hashedPassword);

        // ASSERT
        assertNotNull(user);
        assertEquals("new@amadeus.com", user.getEmail());
        assertEquals("newuser", user.getUsername());
        assertEquals(hashedPassword, user.getPasswordHash());
        assertNull(user.getId(), "ID should be null (will be generated by DB)");
        assertNull(user.getCreatedAt(), "CreatedAt should be null (set by @PrePersist)");
    }

    @Test
    @DisplayName("Should return null when converting null request to entity")
    void shouldReturnNullWhenRequestIsNull() {
        // ACT
        User user = UserMapper.toEntity(null, "hashedPassword");

        // ASSERT
        assertNull(user, "Should return null for null request");
    }

    @Test
    @DisplayName("Should update entity with all fields from UpdateRequest")
    void shouldUpdateEntityAllFields() {
        // ARRANGE
        User existingUser = User.builder()
                .id("user-123")
                .email("old@amadeus.com")
                .username("olduser")
                .passwordHash("hash")
                .build();

        UpdateUserRequest updateRequest = new UpdateUserRequest(
                "newusername",
                "https://new-avatar.com/image.jpg");

        // ACT
        UserMapper.updateEntity(existingUser, updateRequest);

        // ASSERT
        assertEquals("newusername", existingUser.getUsername());
        assertEquals("https://new-avatar.com/image.jpg", existingUser.getProfileImage());

        // Email NO debe cambiar (inmutable)
        assertEquals("old@amadeus.com", existingUser.getEmail());
        assertEquals("user-123", existingUser.getId());
    }

    @Test
    @DisplayName("Should update entity only with non-null fields (partial update)")
    void shouldUpdateEntityPartially() {
        // ARRANGE
        User existingUser = User.builder()
                .id("user-123")
                .email("test@amadeus.com")
                .username("originaluser")
                .profileImage("original-image.jpg")
                .passwordHash("hash")
                .build();

        // Solo actualizar username (profileImage es null)
        UpdateUserRequest updateRequest = new UpdateUserRequest(
                "updateduser",
                null // No cambiar profileImage
        );

        // ACT
        UserMapper.updateEntity(existingUser, updateRequest);

        // ASSERT
        assertEquals("updateduser", existingUser.getUsername());
        assertEquals("original-image.jpg", existingUser.getProfileImage(),
                "ProfileImage should remain unchanged");
    }

    @Test
    @DisplayName("Should not update entity when request is null")
    void shouldNotUpdateWhenRequestIsNull() {
        // ARRANGE
        User existingUser = User.builder()
                .id("user-123")
                .username("original")
                .build();

        // ACT
        UserMapper.updateEntity(existingUser, null);

        // ASSERT
        assertEquals("original", existingUser.getUsername(),
                "Username should remain unchanged");
    }

    @Test
    @DisplayName("Should not update when entity is null")
    void shouldNotUpdateWhenEntityIsNull() {
        // ARRANGE
        UpdateUserRequest updateRequest = new UpdateUserRequest("newname", null);

        // ACT & ASSERT
        assertDoesNotThrow(() -> UserMapper.updateEntity(null, updateRequest),
                "Should handle null entity gracefully");
    }

    @Test
    @DisplayName("Should not expose password in DTO")
    void shouldNotExposePasswordInDTO() {
        // ARRANGE
        User user = User.builder()
                .id("user-123")
                .email("test@amadeus.com")
                .username("testuser")
                .passwordHash("$2a$10$secretHashedPassword")
                .createdAt(LocalDateTime.now())
                .build();

        // ACT
        UserDTO dto = UserMapper.toDTO(user);

        // ASSERT
        assertNotNull(dto);

        // Verificar que DTO no tiene manera de acceder al password
        // (esto es garantizado por el diseño del Record)
        String dtoString = dto.toString();
        assertFalse(dtoString.contains("secretHashedPassword"),
                "DTO should not expose password hash");
    }
}
